/***************************************************************************
 * generate.c
 *
 * Computer Science 50
 * Problem Set 3
 *
 * Generates pseudorandom numbers in [0,LIMIT), one per line.
 *
 * Usage: generate n [s]
 *
 * where n is number of pseudorandom numbers to print
 * and s is an optional seed
 ***************************************************************************/
 
// standard libraries
#define _XOPEN_SOURCE
#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// constant
#define LIMIT 65536

int main(int argc, string argv[])
{
    // Generates usage alert if user does not enter at least one argument (n) 
    // or enters more than the 2 (n and [s]).
    if (argc != 2 && argc != 3)
    {
        printf("Usage: generate n [s]\n");
        return 1;
    }

    // Converts argument n from a string (char[]) to an int.
    int n = atoi(argv[1]);

    // The following calls up the initializer function srand48().
    // It creates a pseudo-random number that is later passed on to drand48().
    // IF: user enters a seed number (i.e. argc = 3), 
    // the following passes it on as an argument to srand48().
    // Seed s is located at position 3 of the argv array, i.e. argv[2]. 
    // argv[2] is first converted from string to int and typecast as a long int 
    // to make room for long seed numbers.
    // Else: if user does not enter seed number, 
    // srand uses the time() function (seconds since 1/1/1970 and therefore
    // typecast to long int) as a seed.
    
    if (argc == 3)
    {
        srand48((long int) atoi(argv[2]));
    }
    else
    {
        srand48((long int) time(NULL));
    }

    // This for loop is run for each pseudorandom number to be generated (i.e. n times).
    // It prints to the screen the output of the function drand48(). 
    // drand48() uses number previously generated by srand function 
    // and generates a random float between 0.0 and 1.0.
    // To generate a random integer (vs float), this is multiplied by LIMIT - the max number 
    // that can be represented in 16 bits - and typecast to an int.
    for (int i = 0; i < n; i++)
    {
        printf("%i\n", (int) (drand48() * LIMIT));

    }

    // success
    return 0;
}
